// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcV50UcRGuBhNjEmg1GVFf56LVs5VPlM',
    appId: '1:189750265519:web:5857336a9e484f2e0ff65a',
    messagingSenderId: '189750265519',
    projectId: 'teamup-34fe7',
    authDomain: 'teamup-34fe7.firebaseapp.com',
    storageBucket: 'teamup-34fe7.firebasestorage.app',
    measurementId: 'G-WKKWBL3FRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXzuN_n24b8xCO09m4A8ARebRWYz75cs',
    appId: '1:189750265519:android:61d41904249b50a00ff65a',
    messagingSenderId: '189750265519',
    projectId: 'teamup-34fe7',
    storageBucket: 'teamup-34fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSU9RcT0lNNV2IsrtwpY-WjxhiiAO4rvI',
    appId: '1:189750265519:ios:00d93eafaf2172df0ff65a',
    messagingSenderId: '189750265519',
    projectId: 'teamup-34fe7',
    storageBucket: 'teamup-34fe7.firebasestorage.app',
    iosBundleId: 'com.example.teamupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSU9RcT0lNNV2IsrtwpY-WjxhiiAO4rvI',
    appId: '1:189750265519:ios:00d93eafaf2172df0ff65a',
    messagingSenderId: '189750265519',
    projectId: 'teamup-34fe7',
    storageBucket: 'teamup-34fe7.firebasestorage.app',
    iosBundleId: 'com.example.teamupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdcV50UcRGuBhNjEmg1GVFf56LVs5VPlM',
    appId: '1:189750265519:web:f4779da40b8352900ff65a',
    messagingSenderId: '189750265519',
    projectId: 'teamup-34fe7',
    authDomain: 'teamup-34fe7.firebaseapp.com',
    storageBucket: 'teamup-34fe7.firebasestorage.app',
    measurementId: 'G-1E5P1XTMGW',
  );
}
